### ISSUE TITLE
Controller that can send tasks in debug mode

### ISSUE THREAD

**Issue by ClayMav** [MissouriMRR/IARC-2019#38]
## Description
Using some intuitive interface, make it possible to send the following commands:
- Takeoff (with altitude)
- Move (with x, y, z offsets)
- Land
- Yaw (with angle of rotation)

## Tasks
- [x] Come up with a layout with Thomas/Clay
- [ ] Finish the various UI components (React)
- [ ] Assemble the UI components into an actual app (React/Electron)
- [ ] Start implementing backend functionality
